CREATE TABLE IF NOT EXISTS store_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    STORE_ID VARCHAR(20),
    STORE_LOCATION VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(50),
    PRODUCT_ID VARCHAR(30),
    MRP DECIMAL(10,2),
    CP DECIMAL(10,2),
    DISCOUNT DECIMAL(10,2),
    SP DECIMAL(10,2),
    transaction_date DATE
);

CREATE TABLE IF NOT EXISTS sales_by_category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_CATEGORY VARCHAR(50),
    total_sales DECIMAL(15,2),
    avg_margin DECIMAL(10,2),
    record_count INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_by_store (
    id INT AUTO_INCREMENT PRIMARY KEY,
    STORE_LOCATION VARCHAR(100),
    total_sales DECIMAL(15,2),
    record_count INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
