version: '3.7'
services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5

    airflow-init:
        image: apache/airflow:2.10.4
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__FERNET_KEY=''
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey123
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/opt/airflow/plugins
        entrypoint: /bin/bash
        command:
            - -c
            - |
              airflow db migrate
              airflow users create \
                --username airflow \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com \
                --password airflow || true

    webserver:
        image: apache/airflow:2.10.4
        restart: always
        depends_on:
            - postgres
            - airflow-init
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__FERNET_KEY=''
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey123
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/opt/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 5

    scheduler:
        image: apache/airflow:2.10.4
        restart: always
        depends_on:
            - postgres
            - airflow-init
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__FERNET_KEY=''
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey123
            - _PIP_ADDITIONAL_REQUIREMENTS=pandas matplotlib
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins
        - ./store_sales_proj/store_files:/opt/airflow/store_files
        - ./script:/opt/airflow/script

        command: scheduler

volumes:
    postgres-db-volume:
